-- Revert mateHub:02-insert-test-data from pg

BEGIN;

TRUNCATE TABLE "M_USER_has_GAME" CASCADE ;
TRUNCATE TABLE "M_USER_has_EVENT" CASCADE ;
TRUNCATE TABLE "M_EVENT_has_LANG" CASCADE ;
TRUNCATE TABLE "event" CASCADE ;
TRUNCATE TABLE "level" CASCADE ;
TRUNCATE TABLE "game" CASCADE ;
TRUNCATE TABLE "lang" CASCADE ;
TRUNCATE TABLE "user" CASCADE ;

COMMIT;
